version: '3.8'
services:
  wallet-app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:wallet@db:5432/wallet
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wallet
      POSTGRES_DB: wallet
    ports:
      - '5432:5432'
  redis:
    image: redis
    ports:
      - '6379:6379'
