version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-app
    volumes:
      - ./src:/wallet-app/src
    ports:
      - "3000:3000"
    shm_size: "1gb"
    restart: unless-stopped
    environment:
      - DB_HOST=mssql
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=wallet
      - DB_NAME=wallet
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=wallet
      - ACCEPT_EULA=Y
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
