version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    shm_size: "1gb"
    restart: unless-stopped