version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wallet
      POSTGRES_DB: wallet

  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"

  wallet-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-app
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: wallet
      DATABASE_NAME: wallet
      REDIS_HOST: redis
      REDIS_PORT: 6379
